### PR TITLE
fix: count with group (#6157)

### LINKED ISSUE #6157: DB.Count函数貌似存在bug
在对某个字段group by后使用DB.Count统计总共条数时，如果group by后只有一个分组， DB.Count函数将获取到该分组下一共有多少条数据（即在sql中使用COUNT(*)时获取的数据）
image

例如这种情况我想通过DB.Count函数得到1（因为数据库中只存在这一天的数据），但是DB.Count函数却返回284（284是数据库中该天数下全部数据的条数）

### PR DESCRIPTION
**Pull request by black-06**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

First created in #4560 and #4809 and fixed in #4885
But due to the modification at f91313436abcfe7a28a488d5d6777b31a94f24fb, it reappeared.
close #6157.

### User Case Description

When `Count` with `Group`, It should return the number of groups

### CODE REVIEW

File: tests/count_test.go [hunk 1]
```diff
@@ -141,8 +141,8 @@ func TestCount(t *testing.T) {
 	}
 	DB.Create(sameUsers)
 
-	if err := DB.Model(&User{}).Where("name = ?", "count-4").Group("name").Count(&count11).Error; err != nil || count11 != int64(len(sameUsers)) {
-		t.Fatalf("Count should be 3, but got count: %v err %v", count11, err)
+	if err := DB.Model(&User{}).Where("name = ?", "count-4").Group("name").Count(&count11).Error; err != nil || count11 != 1 {
+		t.Fatalf("Count should be 1, but got count: %v err %v", count11, err)
 	}
```
Comment (a631807682) [inline tests/count_test.go:146]: I hope to add a test to help us understand what the count in groupby refers to by comparison, for example
```go
 DB.Model(&User{}).Where("name Like ?", "count-%").Group("name").Count(&count11)
```

**Review by a631807682 — APPROVED** [review]

**Comment by 2292384454** [comment]
Yes, I am also troubled by this problem. In which version will gorm officially release this fix?
