### PR TITLE
Fix: Composite primary key with auto-increment value returns 0 after insert

### LINKED ISSUE #4930: composite key auto-increment returned 0 upon Create of new record
## GORM Playground Link

https://github.com/go-gorm/playground/pull/417

## Description

Use Case:
Define table with multiple primary keys (composite key)
Upon New record insert, Get ID of autoIncrement enabled field. 

Issue:
0 returned for autoIncrement enabled field. (Only when the model has 2 fields using primarykey tag)

Example:
Model Defined
image

Test Case:
image

Test Result:
image

### PR DESCRIPTION
**Pull request by truongns**
Fix #4930 workaround for databases that support auto-increment in composite primary key.

- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?
Fix issue https://github.com/go-gorm/gorm/issues/4930

### User Case Description
In MySQL, you can have composite primary key with auto-increment 
For example:

https://github.com/nash90/playground/blob/7a82d16b1b1b626df01cf43089b302de7c2a6bd9/models.go#L63-L70
```go
type CompositeKeyProduct struct {
	ProductPointID int       `gorm:"primaryKey;autoIncrement:true;column:product_point_id"`
	LanguageCode   int       `gorm:"primaryKey;autoIncrement:false;column:language_code"`
	Code           string    `gorm:"column:code"`
	Name           string    `gorm:"column:name"`
	CreatedAt      time.Time `gorm:"column:created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at"`
}
```

Upon insert new record into `CompositeKeyProduct` with the following values:
https://github.com/nash90/playground/blob/7a82d16b1b1b626df01cf43089b302de7c2a6bd9/main_test.go#L26-L30
```go
prod := &CompositeKeyProduct{
		LanguageCode: 56,
		Code:         "56",
		Name:         "Test56",
}

res := DB.Create(prod)
```

expected 
```
prod.ProductPointID: 1
```

actual
```
prod.ProductPointID: 0
```

This Pull Request is aiming to fix the above case

### CODE REVIEW

**Review by a631807682 — COMMENTED** [review]
Can you add more tests to describe it? just like doing in playground.

File: tests/create_test.go [hunk 1]
```diff
@@ -547,3 +547,33 @@ func TestFirstOrCreateRowsAffected(t *testing.T) {
...
+		t.Fatalf("failed to create, got error %v", err)
+	}
+
+	newProd := &CompositeKeyProduct{}
+	if err := DB.First(&newProd).Error; err != nil {
+		t.Fatalf("errors happened when query: %v", err)
+	} else {
+		AssertObjEqual(t, newProd, prod, "ProductID", "LanguageCode", "Code", "Name")
+	}
+}
```
Comment (truongns) [inline tests/create_test.go:579]: @a631807682
I added this test here as per your request.
So with MySQL
Before the fix:
```
newProd.ProductID : 1
prod.ProductID : 0
```
After
```
newProd.ProductID : 1
prod.ProductID : 1
```

File: schema/schema.go [hunk 2]
```diff
@@ -225,6 +225,16 @@ func ParseWithSpecialTableName(dest interface{}, cacheStore *sync.Map, namer Nam
 		schema.PrioritizedPrimaryField = schema.PrimaryFields[0]
 	}
 
+	// If there are multiple primary keys, the AUTOINCREMENT field is prioritized
+	if schema.PrioritizedPrimaryField == nil && len(schema.PrimaryFields) > 1 {
+		for _, field := range schema.PrimaryFields {
+			if _, ok := field.TagSettings["AUTOINCREMENT"]; ok {
```
Comment (a631807682) [inline schema/schema.go:231]: Can we use `field.AutoIncrement`?  What happens when tag is set to `autoIncrement:false`?

File: tests/create_test.go [hunk 3]
```diff
@@ -547,3 +547,33 @@ func TestFirstOrCreateRowsAffected(t *testing.T) {
...
+
+func TestCreateWithAutoIncrementCompositeKey(t *testing.T) {
+	type CompositeKeyProduct struct {
+		ProductID    int `gorm:"primaryKey;autoIncrement:true;"` // primary key
+		LanguageCode int `gorm:"primaryKey;"`                    // primary key
+		Code         string
+		Name         string
+	}
+
+	err := DB.Migrator().DropTable(&CompositeKeyProduct{})
```
Comment (a631807682) [inline tests/create_test.go:559]: never used ?

File: schema/schema.go (hunk 2 above)
Comment (a631807682) [reply schema/schema.go:231]: Can this code be merged with here?
https://github.com/go-gorm/gorm/pull/6127/files#diff-eafe62eae191e88faad4c223c4de9af268c175ee68695872e175b814d7c5baa5L224

Comment (truongns) [reply schema/schema.go]: @a631807682 Thank you for pointing this out, I have fixed the code based on your comment.
- use field.AutoIncrement instead
- merge with [#6127 (files)](https://github.com/go-gorm/gorm/pull/6127/files#diff-eafe62eae191e88faad4c223c4de9af268c175ee68695872e175b814d7c5baa5L224)
- add test for autoIncrement:false

File: tests/create_test.go (hunk 3 above)
Comment (truongns) [reply tests/create_test.go]: I have removed the unused code

**Review by a631807682 — APPROVED** [review]

File: tests/create_test.go [hunk 4]
```diff
@@ -548,6 +548,35 @@ func TestFirstOrCreateRowsAffected(t *testing.T) {
...
+		LanguageCode: 56,
+		Code:         "Code56",
+		Name:         "ProductName56",
+	}
+	if err := DB.Create(&prod).Error; err != nil {
+		t.Fatalf("failed to create, got error %v", err)
+	}
+
+	newProd := &CompositeKeyProduct{}
+	if err := DB.First(&newProd).Error; err != nil {
```
Comment (black-06) [inline tests/create_test.go:573]: This is not rigorous here. When I run the test repeatedly, the inserted record product id is self-increasing, so it will fail.
I suggest to do `DropTable` before `AutoMigrate`.

```golang
if err := DB.Migrator().DropTable(&CompositeKeyProduct{}); err != nil {
	t.Fatalf("failed to migrate, got error %v", err)
}
```
