### PR TITLE
fix(MigrateColumn):declared different type without length

### LINKED ISSUE #5462: Migrate from varchar to text not work
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
image

### PR DESCRIPTION
**Pull request by a631807682**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

close #5462

### CODE REVIEW

File: migrator/migrator.go [hunk 1]
```diff
@@ -404,21 +403,25 @@ func (m Migrator) RenameColumn(value interface{}, oldName, newName string) error
...
+	}
+
 	// check size
 	if length, ok := columnType.Length(); length != int64(field.Size) {
 		if length > 0 && field.Size > 0 {
 			alterColumn = true
 		} else {
 			// has size in data type and not equal
 			// Since the following code is frequently called in the for loop, reg optimization is needed here
-			matches := regRealDataType.FindAllStringSubmatch(realDataType, -1)
```
Comment (a631807682) [inline migrator/migrator.go:419]: Remove `regRealDataType` because it is not match anything after https://github.com/go-gorm/gorm/pull/5088
